# Generated by Django 2.2 on 2019-04-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('angle', models.FloatField(verbose_name='Calculated angle')),
                ('detection_time', models.DateTimeField(verbose_name='Detection date')),
                ('image_file_path', models.FilePathField(verbose_name="File path of the muon's cropped photo")),
            ],
        ),
    ]
