# Generated by Django 2.2 on 2019-04-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='image_file_path',
            field=models.FilePathField(path='/home/cevenkadir/Repos/projectud-1/static', verbose_name="File path of the muon's cropped photo"),
        ),
    ]
