# Generated by Django 2.2 on 2019-04-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0002_auto_20190421_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muon',
            name='image_file_path',
        ),
        migrations.AddField(
            model_name='muon',
            name='image',
            field=models.ImageField(default='muons/muon_2019_4_18_14_17_12_650984.webp', upload_to='muons/', verbose_name='Muon image'),
        ),
    ]
