# Generated by Django 2.2 on 2019-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0003_auto_20190421_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='angle',
            field=models.FloatField(default=0, verbose_name='Calculated angle'),
        ),
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Detection date'),
        ),
    ]
