# Generated by Django 2.2 on 2019-04-21 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0004_auto_20190421_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Detection date'),
        ),
    ]
