# Generated by Django 2.2 on 2019-04-21 19:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0005_auto_20190421_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 19, 22, 48, 314845), verbose_name='Detection date'),
        ),
    ]
