# Generated by Django 2.2 on 2019-04-21 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0006_auto_20190421_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 21, 21, 48, 9, 112760), verbose_name='Detection date'),
        ),
    ]
