# Generated by Django 2.2 on 2019-04-22 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0007_auto_20190421_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 9, 11, 11, 235484), verbose_name='Detection date'),
        ),
    ]
