# Generated by Django 2.2 on 2019-04-22 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0008_auto_20190422_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 9, 47, 41, 345150), verbose_name='Detection date'),
        ),
        migrations.AlterField(
            model_name='muon',
            name='image',
            field=models.FileField(default='muons/muon_2019_4_18_14_17_12_650984.webp', upload_to='muons/'),
        ),
    ]
