# Generated by Django 2.2 on 2019-04-22 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0009_auto_20190422_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 9, 49, 48, 690920), verbose_name='Detection date'),
        ),
    ]
