# Generated by Django 2.2 on 2019-04-22 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_on_internet', '0012_auto_20190422_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muon',
            name='detection_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 22, 10, 38, 7, 195468), verbose_name='Detection date'),
        ),
    ]
